# Generated by Django 2.2.13 on 2020-08-30 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200829_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeTitle', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
