# Generated by Django 2.2.13 on 2020-08-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200830_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationEntry',
        ),
    ]
